### ISSUE TITLE
您好，我在DETReg的作者下看到您问了一个问题，所以想来请教您一下。

### ISSUE THREAD

**Issue by Hongzhaorui** [gaobb/Few-Shot-Object-Detection-Papers#1]
想请教您一下DETReg是如何进行小样本目标检测的训练与测试的，我在源代码里好像没有找到对应的地方。

**Comment by gaobb** [comment]
您好！DETReg 没有公开few-shot 相关的代码，我自己复现的。

**Comment by gaobb** [comment]
您好！DETReg 没有公开few-shot 相关的代码，我自己复现的。

**Comment by gaobb** [comment]
您好！DETReg 没有公开few-shot 相关的代码，我自己复现的。

**Comment by Hongzhaorui** [comment]
好的，谢谢您！
