### ISSUE TITLE
Three missing FSOD papers

### ISSUE THREAD

**Issue by GuangxingHan** [gaobb/Few-Shot-Object-Detection-Papers#3]
[ECCV 2022] [Few-Shot End-to-End Object Detection via Constantly Concentrated Encoding across Heads](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136860056.pdf) [[code](https://github.com/Phoenix-V/coco-rcnn)]
[AAAI 2022] [Meta Faster R-CNN: Towards Accurate Few-Shot Object Detection with Attentive Feature Alignment](https://arxiv.org/abs/2104.07719) [[code](https://github.com/GuangxingHan/Meta-Faster-R-CNN)]
[ICCV 2021] [Query Adaptive Few-Shot Object Detection with Heterogeneous Graph Convolutional Networks](https://arxiv.org/abs/2112.09791) [[code](https://github.com/GuangxingHan/QA-FewDet)]

Thanks.

**Comment by gaobb** [comment]
Thanks very much for pointing out the 3 missing papers. 
I am very grateful if you can provide the results of the corresponding methods on the [MS-COCO ](https://github.com/gaobb/Few-Shot-Object-Detection-Papers/edit/master/mscoco-fsod.md)and [PASCAL-VOC](https://github.com/gaobb/Few-Shot-Object-Detection-Papers/edit/master/pascalvoc-fsod.md) datasets in the format of our leaderboard.

**Comment by GuangxingHan** [comment]
Thanks.

The MSCOCO results are:
|[CoCo-RCNN](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136860056.pdf)| ECCV |2022|R-101|Sparse-RCNN| Fine-tuning |FSOD|5.2/-/16.4/19.2|[PyTorch](https://github.com/Phoenix-V/coco-rcnn)|
|[Meta-Faster-RCNN](https://arxiv.org/abs/2104.07719)| AAAI |2022|R-101|Faster R-CNN| meta-learning|FSOD|5.1/10.8/12.7/16.6|[PyTorch](https://github.com/GuangxingHan/Meta-Faster-R-CNN)|
|[QA-FewDet](https://arxiv.org/abs/2112.09791)| ICCV |2021|R-101|Faster R-CNN| meta-learning|FSOD|4.9/9.7/11.6/16.5|[PyTorch](https://github.com/GuangxingHan/QA-FewDet)|

The VOC results are:
|[CoCo-RCNN](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136860056.pdf)| ECCV |2022|R-101|Sparse-RCNN| Fine-tuning |FSOD|33.5 44.2 50.2 57.5 63.3 | 25.3 31.0 39.6 43.8 50.1 | 24.8 36.9 42.8 50.8 57.7|[PyTorch](https://github.com/Phoenix-V/coco-rcnn)|
|[Meta-Faster-RCNN](https://arxiv.org/abs/2104.07719)| AAAI |2022|R-101|Faster R-CNN| meta-learning|FSOD|43.0 54.5 60.6 66.1 65.4 |27.7 35.5 46.1 47.8 51.4 |40.6 46.4 53.4 59.9 58.6|[PyTorch](https://github.com/GuangxingHan/Meta-Faster-R-CNN)|
|[QA-FewDet](https://arxiv.org/abs/2112.09791)| ICCV |2021|R-101|Faster R-CNN| meta-learning|FSOD|42.4 51.9 55.7 62.6 63.4| 25.9 37.8 46.6 48.9 51.1| 35.2 42.9 47.8 54.8 53.5|[PyTorch](https://github.com/GuangxingHan/QA-FewDet)|

By the way, our FCT (CVPR 2022) has the open-sourced project at https://github.com/GuangxingHan/FCT.

**Comment by gaobb** [comment]
Thanks very much. 
The provided results and the corresponding papers have been updated. In addition, the FCT code is also updated.

**Comment by gaobb** [comment]
Thanks very much.
The provided results and the corresponding papers have been updated. In addition, the FCT code is also updated.

**Comment by gaobb** [comment]
Thanks very much.
The provided results and the corresponding papers have been updated. In addition, the FCT code is also updated.
